version: '2'
services:
    prog_ferias_anuais-postgresql:
        container_name: prog_ferias_anuais-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/prog_ferias_anuais/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=prog_ferias_anuais
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
